---
title: "First Knit"
author: "Aetan Barquero"
date: "`r Sys.Date()`"
output:
  word_document:
    toc: true
    toc_depth: '5'
  pdf_document:
    toc: true
    toc_depth: '5'
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer
  I attended Lancaster High School and graduated in 2025. English was easier for me when compared to math. I enjoy reading and writing so my passion is always greater for english although math is not too dificult. I did best in english because that was the subject I was most interested in. 

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?


### my answer
I have a windows computer at home. In terms of computer knowledge I would rate myself a 7 since. The internet access at home is great. 




## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
My first name is perfectly fine. My name is pronouned Ay-ten.
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
I want to live a stable life and have a family. I am most interested in psychology and studying in order to work in the field. I am working in order to obtain at least a masters in psychology. 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
I have not yet been to any foreign countries however, i do want to visit Iceland one day. I have not been to the military but If I were to be drafted I think I would want to geet drafted to the airforce since I have mutliple friends pursuing or already in the airforce therefore, that is the branch which I have the most knowledge about.   





## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     

 






  




